services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1617
      MYSQL_DATABASE: bookworks
      MYSQL_USER: hojin
      MYSQL_PASSWORD: 1617
    volumes:
      - ./mysql/data:/var/lib/mysql
  postgresql:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: bookworks
      POSTGRES_USER: hojin
      POSTGRES_PASSWORD: 1617
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
